### ISSUE TITLE
What the FOUC is going on?

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#105]
Well folks, we have some amazing performance going on now with lazy loading and server-rendering.  This app is going to be 🔥🔥🔥 .

We have a small issue though, one which plagues all would-be React Server-rendering enthusiasts:
### F   ⚡️ 
lash 

### O   🦃 🌮  <-- I didn't know how to translate "of" to emoji.
f 

### U   👎 
nstyled 

### C   📖 
ontent

FOUC is annoying!! What is it, you ask?  Well, we need to look into the steps that take place when a user requests one of our site's pages.

With server rendering, here is what happens when a page loads:

1. A request is sent to the server for a particular URL.
- The server takes a look at the URL and sees if it matches any of our clientside routes.  If so, it renders a big 'ol blob of HTML and sends it to the client as static HTML.
- Keep in mind, all of this happens _before_ the browser loads the bundle (both css and js).
2. When the browser receives this blob of HTML, it renders it so that we have something to look at very quickly.  A second or two later, our CSS is loaded and the site looks great!

The problem occurs at the end of step 2.  For a split second, the user is looking at our web app with really awful styling and almost no content (the content needs to be loaded from the API)!

So how do dynamic publishing sites get away with being able to server render with dynamic content from an API?

A site like Medium uses some very clever trickery to do away with FOUC.  They inline a subset of their "Above the fold CSS" so that when the html hits the browser, the part that the user sees during that dreaded 2 second period between unstyled and styled content looks pretty darn good.

They also design their components to look good in every state: loading, not loading, etc.  If you notice, on medium when an image is loading, they render a very [pixelated likeness](https://jmperezperez.com/medium-image-progressive-loading-placeholder/) of the original photo with a filter so that it gives a cool appearance (see below).

![Medium Image Loading](https://jmperezperez.com/assets/images/posts/medium-placeholder.png)

So, to make our site equally as amazing, I think we are going to have to get creative.  We are going to have to think like all-star web devs and do away with all the FOUC on our site.

Any ideas?  Would love to see some people take this on.  You could do some research into how other dynamic sites solve this and work with us to make this site something we can all be truly proud of!! What do you say!?

# ⬇️ DOWN WITH FOUC ⬇️ 

😄 😄 😄 😄

**Comment by ghoshabhi** [comment]
Isn't showing a "spinner" one of the options ?

**Comment by kellim** [comment]
It has a LoadingIndicator component that currently shows a spinner with Loading when the main part of the content is loading but it doesn't do that for the entire page like header footer, etc.... so now if you go to different pages on the Heroku site you see the header and footer, etc unstyled.

**Comment by kellim** [comment]
Would [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin)  or [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) mentioned [here](http://stackoverflow.com/questions/34615898/react-server-side-rendering-of-css-modules) on StackOverflow work for the alumni app?

It looks like extract-text-webpack-plugin is already used for the alumni app but maybe we could do something different with it for css? I do not have a full understanding of webpack (yet) to understand what it is doing with the css. SurviveJS mentions using extract-text-webpack-plugin to avoid FOUC [here](http://survivejs.com/webpack/building-with-webpack/separating-css).

**Comment by RyanCCollins** [comment]
Ah ha!  Yes indeed we are using Extract Text Plugin already, but perhaps we need to change the configuration to allow for some inlining of the important styles.  Nice one @kellim !!
