### ISSUE TITLE
Update contributor's emojis

### ISSUE THREAD

**Issue by martin-martin** [udacityalumni/alumni-client#107]
I think these are out-of-date. I wouldn't mind updating them (I think they are sweet ; )

I'd do for now what I (think I) know, but you can notify me here if I'm missing something or made a mistake and I'll gladly fix.

**Comment by martin-martin** [comment]
Question: is there an automated way of doing this? I guess otherwise I'd need people to tell me about their commits, since the site suggests to link each emoji with the related work done: https://github.com/kentcdodds/all-contributors#mandatory

**Comment by RyanCCollins** [comment]
I don't know of an automated way to keep them updated unfortunately.

**Comment by martin-martin** [comment]
Alright, I might just add a little if I get the time and people are encouraged to update themselves more! : )

**Comment by kellim** [comment]
To add an emoji, do you update the README on your local machine then do a pull request? (as opposed to just editing the README on GitHub)

**Comment by RyanCCollins** [comment]
The data is stored in the .all-contributorsrc file in the repo.  You can see that each user has a contributions under their name.  Please feel free to update yours as you see fit!

```
    {
      "login": "adai183",
      "name": "Andreas Daiminger",
      "avatar_url": "https://avatars.githubusercontent.com/u/13679375?v=3",
      "profile": "https://github.com/adai183",
      "contributions": [
        "code",
        "doc",
        "test"
      ]
```
