### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#114]

**Comment by martin-martin** [comment]
Hei @ghoshabhi - if you're interested and see value in that, we could try on this together?

**Comment by martin-martin** [comment]
I have an idea that I'd like to include a carousel at the bottom of the About page where every contributor shares a short sentence about what this project is about for them :)
already made a google form for fetching those gems...
what do you guys think about this idea?

**Comment by RyanCCollins** [comment]
I have man Thiebababa sounds amazing. Can we put a picture of each person there too?

**Comment by martin-martin** [comment]
Yeah, that's what I thought. : )

Here's my draft form: https://docs.google.com/forms/d/e/1FAIpQLSdTqjW5Zs2lIOT9xssrPoL3DnHSmfgB42X9H0qsUGrSPVky-Q/viewform

I'll sleep over it and ask @abhi18 and then maybe tomorrow we can post something like that in the slack channel : )

**Comment by RyanCCollins** [comment]
This sounds awesome, can't wait to see it materialize.  Let me know if you need help coding the UI

**Comment by ghoshabhi** [comment]
@ghoshabhi is my actual ID @martin-martin !! :p I don't know how my old account (@abhi18) has reference here!

**Comment by martin-martin** [comment]
The form is live on slack! and small improvements visible in the dedicated devlopment branch. : )
