### ISSUE TITLE
error starting the app on Windows 10

### ISSUE THREAD

**Issue by zhangtreefish** [udacityalumni/alumni-client#119]
I expected: after running `npm run setup` and `npm run start`, the app will start at localhost:1337; 
What actually happened: I got an error about webpack-dev server. The detail is in the log file: 
[npm-debug.txt](https://github.com/udacityalumni/alumni-client/files/546794/npm-debug.txt)

Details on the background:
1) If I reset git to earlier commits, the app did render; however, in that case, the middle section was missing, and there was the red "Failed to fetch" error alert;
2) I use nodist for node version control. Here are outputs of checking node, npm, and webpack-dev-server:

```
C:\Users\Treefish\alumni-client>nodist -v
0.8.5

C:\Users\Treefish\alumni-client>node -v
v5.2.0

C:\Users\Treefish\alumni-client>npm -v
3.10.7

C:\Users\Treefish\alumni-client>webpack-dev-server --help
webpack-dev-server 2.1.0-beta.9
webpack 2.1.0-beta.19
Usage: http://webpack.github.io/docs/webpack-dev-server.html
(blah blah)
```

**Comment by ghoshabhi** [comment]
I changed to use nvm and still no luck. I too get the same error!

**Comment by zhangtreefish** [comment]
Yes, I have been wanting to contribute in however small ways; but perhaps I should start learning webpack-dev-server.

**Comment by RyanCCollins** [comment]
If you'd like this week we can debug it together.  I am not too familiar with Windows, but perhaps I can help.

**Comment by RyanCCollins** [comment]
One thing you can try is starting the dev server on another port or from localhost.  

Within the webpack.config.babel.js:
```
const PORT = process.env.PORT || 1337;
const HOST = '0.0.0.0'; // Set to localhost if need be.
```

**Comment by zhangtreefish** [comment]
I changed 1337 to 1447: same error;
I changed 1337 to 1447 and 0.0.0.0 to localhost: same error. 
Doesn't the fact that the app would render somewhat when reset to earlier commits mean that the issue is not with the port?

**Comment by marcelklehr** [comment]
Just my two cents: I'd try running `npm run dev` directly to see what the script that returns exit code 1 has to say. (If this is totally obvious and you're way past that, please ignore this comment ;) ). Also, it could be that Windows' firewall is denying access to opening ports, perhaps that's why reinstalling solved this for some people?

**Comment by RyanCCollins** [comment]
Yes it could indeed be the firewall. Perhaps some of our more recent configuration doesn't agree with Windows. Recently we updated React hot loader because it was failing to work. 

I have a few ideas @zhangtreefish and will reach out to you.

**Comment by zhangtreefish** [comment]
@marcelklehr @RyanCCollins : Running `npm run dev` produced the same error message. About firewall, I [added](url) `C:\Program Files (x86)\Nodist\v-x64\5.2.0\node.exe` to the list of 'Allow Apps to communicate through Windows Firewall' at 'Systems and Security/Windows Firewall/', and got the same error. I am not sure if the node.exe is the right 'executable' of our app.

**Comment by marcelklehr** [comment]
This appears to be an issue with nodist, after all, see my comment at https://github.com/marcelklehr/nodist/issues/177#issuecomment-257090109

**Comment by ghoshabhi** [comment]
@zhangtreefish : I just used [Yarn](https://yarnpkg.com/en/docs/install#windows-tab) to install the packages and it worked like a charm. I think after the installation you would have to do `npm install -g yarn`, and after that just cd into project directory and type `yarn` and it works like magic! Just make sure you're using Node 5.2.0! 😄

**Comment by zhangtreefish** [comment]
@abhi: Yarn worked for starting the app!  
@RyanCCollins: However, `yarn test` produced the following:
![onyarntest](https://cloud.githubusercontent.com/assets/10746052/20855677/a9296dd6-b8c5-11e6-890f-b1d9d777a4e5.jpg)
I found [this link](https://github.com/gotwarlost/istanbul/issues/677) and tried istanbul as in the branch test_config. However, running `yarn test` now produced neither error nor test report.
