### ISSUE TITLE
Profile Page: Cancel button not working for Public Profile Toggle

### ISSUE THREAD

**Issue by kellim** [udacityalumni/alumni-client#131]
On my [Profile](http://udacity-client.herokuapp.com/me/profile) page (that link will take you to your own profile page on the server if you are logged in), if I change the toggle for Public Profile and click cancel, it acts as if it saves it instead of cancelling. 

So, if someone were to toggle their public profile either on or off and change their mind by clicking the cancel button, it doesn't cancel it.

**Comment by RyanCCollins** [comment]
Sounds like a state bug.  Maybe someone can track [this down](https://github.com/udacityalumni/alumni-client/blob/master/app/src/containers/UserProfileContainer/reducer.js).
