### ISSUE TITLE
Add footer to design

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#14]
We need to implement a sitewide footer component.  (See below for a demo mockup)

**Comment by RyanCCollins** [comment]
We could have some fun with this!  If someone wants to step up and help design a flashy footer, that would be fantastic.  Thanks!

**Comment by RyanCCollins** [comment]
I think this would be a great first feature for anyone looking to jump into the project.  I am going to make a little mockup in a few.

**Comment by kellim** [comment]
I would like to try this one. I assigned it to myself.

**Comment by RyanCCollins** [comment]
Great!  I think this is an awesome first step for you.  I had talked to @martin-martin about doing it, but that;s okay I will communicate to him that he'll be doing something else.  I think we can have some fun with this. Customizing the social icons, for example, could be fun.  Let me know if you need some help.  We could do that in a pairing session.

**Comment by kellim** [comment]
Thanks, I will try to figure it out on Codepen first, and I will let you know when I get stuck! Sorry @martin-martin. Also, should the social icons have links at this point, and if so should they link to the main Udacity social media pages?
* `https://www.facebook.com/Udacity`
* `https://twitter.com/udacity`
* `https://www.linkedin.com/company/udacity`

**Comment by forbiddenvoid** [comment]
@kellim: For right now, yes those icons should link to those pages.

**Comment by martin-martin** [comment]
Haha! @kellim, no worries!!! I'm very happy that you decided to do this, I'm sure I'll find something else to do ; )

**Comment by RyanCCollins** [comment]
Note: there is now an app footer component that shows the text Udacity Alumni Web App.  Please work off of this rather than the old component.  Looking forward to seeing progress on this!

**Comment by kellim** [comment]
Got it. Do we want it to say "Udacity Alumni Web App"? Asking because it is not in the mock. And  does the heart need to have a gradient or can it be the heart that is already in the text with a solid red color via css? Thanks!

**Comment by kellim** [comment]
I found the ❤️  but still need to know if we want to keep "Udacity Alumni Web App" in the footer.
