### ISSUE TITLE
Add Single Article Route

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#15]
The articles are now hooked into the API.  We need a route for viewing a single post.  Right now, when you click on one of the featured articles, it brings you to a blank route.

The single post view needs to hit the api to load the post because it needs to be accessible from a search engine.  You can search for post by the slug that is passed in the URL.

**Comment by RyanCCollins** [comment]
We have already mostly done this one in the demonstration we gave.  The code and mockup can be found here: https://github.com/udacityalumni/resources/wiki/React-Training#demonstration This is mostly static content, but the challenge will be hooking it up to the API.  I would be happy to help with this one during a Pair Programming session.

**Comment by zhangtreefish** [comment]
i@RyanCCollins: That will be great! I have requested a pair programming with you tomorrow.  I have been working on this, using <Link to='/articles/:articleId' />. Shall I push the half-baked branch to github?

**Comment by RyanCCollins** [comment]
Yes please!  Looking forward to tomorrow!!

**Comment by RyanCCollins** [comment]
Yes please!  Looking forward to tomorrow!!

**Comment by zhangtreefish** [comment]
Pushed single_post_route. It does not render the single post view yet. (:

**Comment by RyanCCollins** [comment]
that's okay, I am sure it will soon 👍

**Comment by zhangtreefish** [comment]
feat_single_article branch is my solution to issue #15, thanks to @RyanCCollins ' help through pair programming. I will fine tune the view in the next few days. Please advice and critique liberally.

**Comment by RyanCCollins** [comment]
Thanks @zhangtreefish we may come back to this one later, but am going to put it on the done board for now.  Let me know if you'd like to try your had at something else!!  Thanks so much for your contributions.  Make sure to put that on your resume!
