### ISSUE TITLE
Single Article on Mobile Device - Text overflowing content area

### ISSUE THREAD

**Issue by kellim** [udacityalumni/alumni-client#156]
In a Single article, if there is a long word like Demonstration in the title, then it will overflow the content area. 

![singlearticletextoverflowing](https://cloud.githubusercontent.com/assets/2024584/20415871/ff12ac26-acef-11e6-9902-d6c178d27c42.PNG)

This was tested on an iPhone 5.

**Comment by JamesIves** [comment]
Was this solved already? If not I can take this one.

**Comment by kellim** [comment]
I don't think it is solved.

**Comment by JamesIves** [comment]
Excellent, I'll take a look at this in the morning then.
