### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by martin-martin** [udacityalumni/alumni-client#160]
Tried to add emojis to the About page content and it seems it doesn't display.

I might not be in on a secret of how to do this, though. If so, please accept me into the circle of knowledge!

**Comment by RyanCCollins** [comment]
Hmm, you should be able to render emoji to the screen with relative ease.  I don't think that there is any secret to it.

**Comment by JamesIves** [comment]
How were you trying to display them?

**Comment by martin-martin** [comment]
I tried to write like that `:joy:` in the JSX (now it's Markdown).

What's the correct way to include them?

.

**Comment by martin-martin** [comment]
whoops, let me try that again, like so : joy :
(without the spaces)
`:joy:`

**Comment by RyanCCollins** [comment]
Oh I see.  You need to actually include the Emoji character.  It will not automatically convert the : joy : thing to an emoji.  Try the emoji keyboard on a mac with: `ctrl cmd spacebar`

**Comment by martin-martin** [comment]
Gotcha! I added this and made it all good.
