### ISSUE TITLE
Navigation Close Icon Expectations

### ISSUE THREAD

**Issue by JamesIves** [udacityalumni/alumni-client#166]
When the screen is within 720 and 860 pixels wide the navigation displays some strange behavior. Under 720 pixels if the burger icon is pressed the entire screen is taken up by the navigation, and in its place of the burger icon the close icon appears, which is good. 

However between 720 and 860 the close button moves onto the actual pull-out menu its self, and the existing burger icon shifts to the other side of the screen, as a user this behavior likely would not feel expected. See the storyboard below:

![Navigation Before](http://i.imgur.com/TGCIlM2.jpg)

![Navigation After](http://i.imgur.com/anNiF8q.jpg)

I propose making it so the burger icon is removed entirely, and allow users to click off the pull-out menu by selecting the body area to close it, but I'd like to hear what others think.

**Comment by RyanCCollins** [comment]
Yeah, that sounds like a good plan.  Hide the burger menu and add a click handler to the document.body to close it.  Is that something that you think you can implement?

**Comment by JamesIves** [comment]
On it
