### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#17]
We need to transition the CMS prototype into the client app.  Most of the hard work has been done, but hooking this into the API will be quite an accomplishment.

**Comment by RyanCCollins** [comment]
Awesome job getting this hooked up.  @adai183 can you tell us a bit about what else needs to be done?  The API is ready to accept articles, so we could setup the action creators in the container to connect and pass in an onsubmit?  Is there anything else we need to watch out for?

**Comment by adai183** [comment]
Awesome.
Go ahead and hook it up to the backend.
At some point we will have to polish up the cms editor interface and make it more intuitive.

I am really excited to see this work. Looking forward to get feedback from fellow udacians.
