### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#18]
We will need a route for user's to access their profile information. 

Keep in mind, there are three classes of users and no mockups for this yet, so only implement common functionality until further notice.

**Comment by bryanj4** [comment]
I can work on this.

**Comment by RyanCCollins** [comment]
Cool!  Let's see if we can get some mockups, but that sounds great!

**Comment by zhangtreefish** [comment]
How about adding a field for user showing projects inviting collaboration?

**Comment by RyanCCollins** [comment]
Yeah, that sounds cool.  We have a bit of freedom here to design this how we want.  I say we start with a basic design first and then use a bit of that creative freedom!  Great idea!  Is this something you want to help with @zhangtreefish ?  I was thinking of making some mockups of it today.

**Comment by bryanj4** [comment]
I am thinking about the design for the user profile. 
I'm thinking about including settings for 
* password recovery 
* email change  
* name change
Also there should be room for a profile picture upload along with a description. 

I was also thinking about a feed of the articles you create as well when you are the user you have the ability to go back and edit and if you're not then there is the user's picture, description, article feeds and project collaboration.

**Comment by RyanCCollins** [comment]
I like all that Jake!!! Please run with it.  The articles is a great idea.  I think we will end up with a few sections in the profile, as shown in the mockups.

Oh and by the way, here are the mockups.

![User Profile](https://github.com/RyanCCollins/cdn/blob/master/alumni-webapp/user-profile.png?raw=true)
![User Profile Editing](https://github.com/RyanCCollins/cdn/blob/master/alumni-webapp/user-profile-editing.png?raw=true)

**Comment by martin-martin** [comment]
Hei, here's an interesting project that one alumni made: https://nd-sharables.herokuapp.com/
I've sent him a message too, maybe he feels like collaborating on this.
Not sure this should be integrated into the user profile, or instead be maybe a separate page - what do you think? : )

**Comment by RyanCCollins** [comment]
That is so cool!  I love that.  I would love our web app to combine all of these ideas into one official app.

**Comment by zhangtreefish** [comment]
@RyanCCollins: I'd love to! My preliminary thinking: the ProjectEditorPage will mirror CmsEditorPage; projects will have the following fields: what-app name and description, who-app audience, why-app purpose, how-required skill set, looking for- intended target Udacity student cohorts(a particular Nanodegree and project completion level),  where-github repo.

**Comment by RyanCCollins** [comment]
@zhangtreefish sounds great.  I will come back to this tomorrow as I will be spending most of the day compiling all of this info.

**Comment by bryanj4** [comment]
# Questions

1. Do we want any user profile as long as it is there to be viewed? I say yes but I want everyone's input. 

2. Also I was thinking of user levels from someone logged in vs public vs private data. The data level permissions could be based on critical information such as email address, etc. Does anyone else think this is a good idea?

**Comment by RyanCCollins** [comment]
Yeah, so we do have a role system.  For the most part, you can just design it as if you are expecting a user object to be passed in as a prop from the app (I just got auth hooked up).  The authentication and the role system will be maintained at the app level, not in the user profile so you shouldn't really have to think too much about how this works.  We will protect certain routes at the routing level.
