### ISSUE TITLE
Goal of Udacity Alumni Site

### ISSUE THREAD

**Issue by bryanj4** [udacityalumni/alumni-client#19]
I think it is cool that we're building this app but I guess I missed the main vision for the purpose of work. Could you relay the purpose @RyanCCollins and @forbiddenvoid?

**Comment by RyanCCollins** [comment]
I will refer to David to give an official goal, but my goal is to connect Udacity Alumni in a meaningful way.  Great idea @bryanj4 !

**Comment by JamesIves** [comment]
Certainly think some context would really help!

**Comment by zhangtreefish** [comment]
I hope this site will help Udacity students to experience collaborative projects.

**Comment by RyanCCollins** [comment]
Hi @zhangtreefish I agree!! What else does every one hope for.  Ultimately, this is our project and your input is super valuable.  This application is something that all of us will hopefully use in a meaningful way to connect with each other.

**Comment by xadahiya** [comment]
We can use the site to share post graduation experiences, like what cool projects they are working on. It will inspire other students to keep on learning and if they want they can collaborate too.

**Comment by bryanj4** [comment]
I'm thinking this can be a networking/collaboration hub of Udacity alumni so we can help each other advance in life and in our jobs.

**Comment by James-Gallagher** [comment]
We are not just a group of individuals, we are a community. A community consisting of like-minded individuals who are constantly learning, and putting the skills they have learned into place. The Udacity Alumni Web Application was designed to host a community hob, where we can collaborate, and perceive things differently.

The Community will mean we can share all of our recent graduations, all of our new projects and news, in a more visual manor, as opposed to in a large amount of channels. This app will change the way we collaborate and think as a community, instead of just being a fun project to participate in.

**Comment by martin-martin** [comment]
I see the webapp as a "first-in-many"-adventure, which can take the project-based learning of the NDs to a next level.

Projects done collaboratively with other alumnis give us the chance to learn and practice some skills that I think are essential for the "real-life" work as software engineers. We built stuff in the NDs, but a lot of the setup, organization, and preparation has been done for us.
Building something like this from scratch, and in collaboration with others, holds a ton of new and exciting aspects to learn about and figure out. : )

---

In a way I see this project as a **Capstone Project**, our combined graduation task. It's that first job out of university when you realize that _sure you learned a lot, but there are still all those other aspects to working that you maybe never even thought about_.

I find it also very important that it is a **real project with actual value**. I've seen a lot of capacity and potential among Udacity students, and I find it beautiful when some of this is brought together and employed to make an actually useful project.
I think that's another aspect of "real-life" (or at least of how I'd want it to be).

---

Working as a Team, and creating value for the Udacity community, is in my opinion something that has the potential to benefit all those that are working on it, as well as all those future-alumnis out there and everywhere in the world ; )

**Comment by RyanCCollins** [comment]
@martin-martin Yeah! I have always felt that way.  That was the main reason we started Hacksmiths, to gain collaborative experience.  A couple people got jobs out of it too!  I totally agree that the learning doesn't really even start until your working with other people.   Nice post!!

**Comment by adai183** [comment]
Wow!
You guys made my day! 
This is so inspiring. Thanks for making this whole thing more meaningful. 
:-)

**Comment by baker-natalie** [comment]
It's pretty much already been said, but I am really hoping to help create and take advantage of opportunities to collaborate and gain experience that will help us advance our skills and careers. It seems that is exactly what this project is already doing =)

**Comment by ghoshabhi** [comment]
There is enough already said here about the goal, I will like to share what I feel/expect from this project. 

I feel that this project will be very useful for the existing Udacians to connect amongst each other while the app is being built. There is absolutely no doubt that the final product is going to be utterly useful to the future graduates.

But during the process, I hope to learn from the development team and wish to connect with the fellow Udacians! 😊

**Comment by forbiddenvoid** [comment]
Hey everyone! I'm glad to see so much excitement and energy from this project! If you're curious about the goal/motivation for this, here's what I would say.

1. We need an alumni landing page to house news, updates, and information that is relevant to the interests of Udacity Nanodegree Alumni. 

2. We need an opportunity for alumni to get practical, real world experience with their chosen fields. The app doesn't cover everything for that, but it's a good place to start.

3. If we want to have more project opportunities, it's important for us to try something and see where the challenges are. I've already learned a lot about what works and doesn't for these kinds of distributed team projects.

4. The app will server as a platform for some future alumni-based projects and eventually will be a place where alumni can find each other to work on their own projects. Right now, we're only building the CMS system, where we can place blog posts and news for alumni. In the future, we'll be adding additional features as components into the platform.

Let me know on Slack if you still have questions!
