### ISSUE TITLE
Failing Test ErrorAlert

### ISSUE THREAD

**Issue by bryanj4** [udacityalumni/alumni-client#20]
app/src/components/ErrorAlert/tests/index.test.js:
* Test suite failed to run 

Cannot find module 'grommet/components/notification' from 'index.js' from `app/src/components/ErrorAlert/index.js:4:47`

I fixed the issue and will be submitting a PR.

**Comment by RyanCCollins** [comment]
Thanks man!  This one kinda makes me nervous that your installation is foobarred, because the notication component is working for a few of us.  Can you check your node modules folder `grommet/components/notification`, should be in there, or try to reinstall?

**Comment by bryanj4** [comment]
Yes but you need to be grammar conscious because Linux is picky. You need to capitalize Notifications and Button

**Comment by RyanCCollins** [comment]
Note that this has been fixed in : https://github.com/udacityalumni/alumni-client/pull/27
