### ISSUE TITLE
Beginner's Guide: Meaning of the Labels

### ISSUE THREAD

**Issue by martin-martin** [udacityalumni/alumni-client#21]
I'd like to see the webapp as a low-entrance project making it possible for many many alumnis of different levels of experience to contribute.
I'm currently learning a lot to get up to speed, and thought a **legend explaining the labels** could be something useful.

So here's what I currently think I've figured out (please correct and complete!):

- `discussion`: A topic that is (hopefully) worth thinking, talking, and deciding about.
- `question`: Something you were wondering about. This could be a question about a specific feature you think would be cool for the app, or also a more general question (like the [_what's all this for?_](https://github.com/udacityalumni/alumni-client/issues/19))
- `help wanted`: This issues needs personnel! Take a look, and if you like what you see it would be great if you could hop on the train : )
- `in progress`: This one is not _quite_ ready to be worked on. Something's still pending (e.g. a "good-to-go" response from the official Udacity side)
- `ready`: Here's an issue that you can start working on right now. Start digging freely!
- `enhancement`: Working on this one will make the whole project become a better version of itself. Could be new features or improvements of already existing ones.
- `bug`: Something's going wrong here. This needs a fix in the code.
- `invalid`: The issue raised is not actually an issue. (explain why!)
- `wontfix`: This is a hearty acknowledgement that something is not working, with the clarification that it's not worth the effort to fix it or that it would stray the project elsewhere (explain why!)
- `duplicate`: This issue/question already came up and is discussed elsewhere (include a link to find that "elsewhere")

Labels can be generated in the `Labels` tab. And [here is](https://github.com/FakeItEasy/FakeItEasy/wiki/Issue-labels) how someone else is using them.

**Comment by RyanCCollins** [comment]
Awesome!! Thanks so much for taking the time to do this!

**Comment by bryanj4** [comment]
I tried finding the location to add a label but for some reason I couldn't add a label

**Comment by martin-martin** [comment]
@bryanj4: You should be able to add Labels [here](https://github.com/udacityalumni/alumni-client/labels). Not sure about permissions for this, but I was able to add `discussion`.
Under the _Issues_ tab there is _Labels_ button that then features a green _New Label_ button.

**Comment by bryanj4** [comment]
@martin-martin as a member apparently I had less permissions than a non-member when I had no repository access. Issue was fixed and we'll be attaching proper labels for now on.

**Comment by martin-martin** [comment]
Hei @bryanj4 - I'd like to keep this open, since I believe a few people who are new and not so experienced could maybe benefit from reading about the labels (that was my initial intention when writing this post).

There might be a better place for it maybe - such as the wiki - and eventually we can move it there. But for now it seems to make sense to me to sit around here right next to where one will actually see the labels.

**Comment by martin-martin** [comment]
Moved this information into a wiki page: https://github.com/udacityalumni/alumni-client/wiki/Github
