### ISSUE TITLE
Responsive Scaling

### ISSUE THREAD

**Issue by JamesIves** [udacityalumni/alumni-client#3]
Lots of issues with responsive components of the page. Images are getting the incorrect aspect ratio and there's a lot of overflow. 

This is something I can look into unless somebody already is.

**Comment by RyanCCollins** [comment]
This was just meant to be a demo to get you guys started, not meant to be a beautiful production ready piece.  This would be a great thing to start working on, however.

**Comment by RyanCCollins** [comment]
@JamesIves I have created a new ticket and am going to close this one.  We need a few people to work on the mobile design of the site.  Would love some help on that!  Thanks!
