### ISSUE TITLE
Mentoring, Careers, Meetups

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#35]
I'd like some idea of the UI and data models we will need for these sections so that I can start making some tickets and specifications

**Comment by martin-martin** [comment]
I'd like to contribute on this one. Just saying! : )

**Comment by martin-martin** [comment]
I'll also leave this here for interested people to check out. A Udacity student made this one and it's quite sweet I think: https://connect-udacian.firebaseapp.com/

**Comment by forbiddenvoid** [comment]
We're going to hold off on these for right now. Let's get the articles and editor functioning first. The meetups applet is going to be pretty complex, but mentoring and careers will likely be close to static content (just created from the CMS)
