### ISSUE TITLE
Updating the Wiki

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#36]

**Comment by forbiddenvoid** [comment]
We need some folks to help us update the wiki inside github. This is a great place for new user resources, set up guidelines, etc. I'd like to keep these kinds of materials out of the open issues as much as possible, because I think it detracts from the workflow. 

If this interests you, comment here in this particular issue. Once we get a couple of people, I'll close this and we can start opening issues for specific Wiki needs. Thanks!

**Comment by martin-martin** [comment]
I'm up for doing some wiki-writing. : )

(just want to mention that it made it easier for me to step into thinking about doing something through posting a comment here in the working repo. The wiki is "something else" and more static, while here that's the place where things are happening, where people come by (and also respond) etc.  - I understand that's not the point of the Issues and might make them too convoluted. However, some of us are beginners in this type of collaborative work, so I think it's important to try to make the step across easier. 
Just as a thought to consider - maybe there's another way to achieve something like this without filling up the Issues with conversation. Like me now. Ah...)

**Comment by forbiddenvoid** [comment]
lol, @martin-martin. Issues are for conversation, so don't worry about that. I think we can make the wiki the source of truth for things like code conventions etc. They're criminally underutilized in a lot of projects, and the issues board tends to get clogged just like this. 

My thought is that the README should contain a link to the wiki for common things. We just need to be diligent about keeping it updated.

**Comment by kellim** [comment]
I am interested in updating the wiki too, but I am still learning so I don't know if I will be able to solve the wiki issues, or just write as I go along to explain things from the perspective of someone who is new to collaboration, and tools like grommet, generators, etc.
Also, a silly question - do you update the wiki in the browser? I don't see a way to do a pull request updating the wiki in the browser.

**Comment by martin-martin** [comment]
Whoa! Yes @kellim !! : D
I just had the same question: https://udacityalumni.slack.com/archives/alumni-web-app/p1475739823000905

Okay @forbiddenvoid, ha! : )
It just seems easier with all the notification and people responding and such. I understand that it happens here more than in a wiki. (e.g. much easier to just post something here, as accidentally just exemplified by kellim and me)

**Comment by adai183** [comment]
@martin-martin : GitHub doesn't support pull requests for the wiki repository. 
There are solutions around it. But I think they are to complicated.
I think we can give push permission to people willing to take care of the wiki.  I don't have admin permissions for the repo. But I will ask @RyanCCollins  to give you and @kellim push permission.

**Comment by RyanCCollins** [comment]
I just do it all in the browser!!

**Comment by martin-martin** [comment]
Hei Ryan - I think I don't have edit rights in the general wiki (udacityalumni/resources)
Couldn't find an edit button there.
