### ISSUE TITLE
Not Found Page

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#40]
I have a really fun task for anyone who wants to take it.  Maybe @martin-martin since @kellim is doing the footer you could do this!!

When we stumble onto a route that points to no component, it renders the NotFoundPage route with the text Not Found.  You know how most websites have a 404 page?  We could do something like that for this app and have some fun with it!  Github for example has the [octocat](http://blog.camillechurch.com/github-404-star-wars-parallax/).  We could do the UdaciCat (dumb idea, but you get the point!)

What do you think @martin-martin ?  Sound like something you'd like to take charge of??

**Comment by martin-martin** [comment]
That sounds really exciting! : D
I'd gladly take this over!

**Comment by adai183** [comment]
Congrats! @martin-martin 
Awesome creative 404 page !

**Comment by martin-martin** [comment]
Okay, maybe I have an idea for an image. I'll work on this : )
