### ISSUE TITLE
Reducing Hot Reload Time

### ISSUE THREAD

**Issue by adai183** [udacityalumni/alumni-client#42]
I am a bit frustrated because on  my machine hot reloading takes about 7 seconds every time I change one line of code. Doing front end work this is very tiresome.
Question: Does webpack actually rebundle both source **and** dependencies everytime I change a line of code?
If yes we might look for a different webpack config. Maybe it is possible to tell webpack not to touch our third party dependencies more than once.
I will investigate on that topic.

**Comment by RyanCCollins** [comment]
Hey @adai183!  I have a few performance enhancements we can try, but they will make the build even more convulated.  Let me try a simple one first and see if that helps you.  I just benchmarked and it reduced the time by a factor of 30%, so hopefully that will be a marked improvement for you.

**Comment by RyanCCollins** [comment]
Go ahead and give this a pull to try it out.

**Comment by adai183** [comment]
ok.
Also just cam across [this](https://medium.com/@soederpop/webpack-plugins-been-we-been-keepin-on-the-dll-cdfdd6cb8cd7#.r8wphmdmbl)
I want to give the DLL plugin a try.

**Comment by RyanCCollins** [comment]
Chunking is another approach I have taken as seen on my portfolio project: https://github.com/RyanCCollins/ryancollins.io This is part of the production build only, however.  DLL was too daunting for me, but would love to see you get it right.

**Comment by adai183** [comment]
wow! Huge improvement with the cheaper source map dev-tool.
DLL looks nasty and documentation is pretty bad. But I will give it a try.

**Comment by RyanCCollins** [comment]
Sweet!
