### ISSUE TITLE
npm WARN

### ISSUE THREAD

**Issue by zhangtreefish** [udacityalumni/alumni-client#59]
The following appears after running 'npm run setup' but does not prevent the app from running. Running `npm install --global webpack webpack-dev-server` at the command prompt [eliminates the part of the  warning about webpack](https://github.com/webpack/webpack-dev-server/issues/349), but I wish though to know how it can be addressed inside package.json:
`+-- redux-auth-wrapper@0.8.0
`-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.19

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN babel-plugin-webpack-loaders@0.8.0 requires a peer of webpack@>=1.12.9 <3.0.0 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.`

**Comment by RyanCCollins** [comment]
Indeed, that package is out of date.  So far, it seems to be working however.  We may want to keep an eye on it, but we do need that package for our test suite, so it needs to stay the way it is for now.

Thanks for your input!!
