### ISSUE TITLE
Expect that after posting an article, it redirects the user.

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#64]
Posting an article doesn't redirect anywhere, which is an awkward experience. It should redirect either to the content dashboard or back to the main page. Dashboard is preferable.

**Comment by zhangtreefish** [comment]
@ryancollins: On my PR addressing  issue #64 Redirecting:will there be a route such as `/users/:id/content-dashboard` in the future? For now I had it redirected to admin's, not sure if that is right.
