### ISSUE TITLE
Expect the search bar to have a placeholder and popout on hover.

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#69]
Hover over search icon should pop out the search box. Some placeholder text: "What would you like to search for" or something like that.

**Comment by RyanCCollins** [comment]
There is an option to keep the thing open all the time.

I added a placeholder.  Making it pop out on hover can be done at the grommet level, so I will take a look at some point.

**Comment by forbiddenvoid** [comment]
Yeah, I think hover is the best bet here. I would prefer for it not be open all the time.
