### ISSUE TITLE
Need to add distinction between different user classes

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#72]
Let's make sure we start implementing the differences between users, creators and admins. Regular users shouldn't see the post an article link on the main page.

Ryan, can you get us set up with test users of each type?

**Comment by RyanCCollins** [comment]
Yeah, in fact @swaption2009 was talking to me about this.  Basically, on the API side we need to make a determination about what models are available to who.

Then, on Front End side, we need to have different routes for specific types.  This is in fact already configured, just not yet setup.

https://github.com/udacityalumni/alumni-client/blob/master/app/src/routes.js

**Comment by forbiddenvoid** [comment]
This is good. Can this be done within a page as well? Different components displayed for different user types?
