### ISSUE TITLE
Clicking menu items refreshes the page.

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#73]
Let's not do this. The sooner we can nip this in the bud the better off we are.

Can we wrap the pages up so that they live inside of a root container?

I don't that we're using routing here, but ideally all of the functionality lives inside of one single page. Can we simply tell the browser we're at a different location without actually _going_ to a different location. 

Basically, we're reloading a bunch of resources on the page that are fundamentally static, and we shouldn't be.

**Comment by adai183** [comment]
The idea is to do use webpack and react-router for lazyloading and code-splitting. Webpack will break the huge bundled js into chunks specific to each route. In production each route will only load the js it really needs. 
This gives us a massive performance gain.
I am sure @RyanCCollins can tell us more about this.

**Comment by RyanCCollins** [comment]
Am not sure what the question is.  The routing is handled by React router, so it's all done with javascript.  When we get to production, we will performance optimize it like Andy said.  When you use react router to push a new route using the history API and the current setup, it will transition using JavaScript and NOT perform a full page reload.  This is why it is much faster than the majority of websites.

**Comment by RyanCCollins** [comment]
This is fixed, so will set to done for now.  Thanks @forbiddenvoid and @adai183 !!

**Comment by RyanCCollins** [comment]
I added a check here to see if any article were loaded before refreshing:

```
    if (!featuredArticles || !featuredArticles.length > 0) {
      actions.loadFeaturedArticles();
    }
```
