### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#8]
We need some help with creating mobile design for the entire site.  We should focus on the mobile navigation and also potentially move the profile section into a menu on the navigation.  We will also need to add mobile responsiveness to images and stuff like that.

**Comment by RyanCCollins** [comment]
Since we don't have any movement yet on this, I think I am going to make this one of my assignments and I would love some input.  An example of what I am thinking is located here: https://corporate-dashboard-client.herokuapp.com/

**Comment by RyanCCollins** [comment]
Again, I'd love some help on this one.  This is probably the most important ticket we have now.  I will get us started and would love someone else to come jump in to help!!

**Comment by RyanCCollins** [comment]
Note, I have decided to get some progress going on this and will update the repo soon.  I could still use help with making the site responsive!!

**Comment by RyanCCollins** [comment]
We seriously need help on this.  This will be mostly CSS and feedback on the current mobile design.  Is there someone, or a group of people who can stand up and volunteer to help us to get a killer mobile design?

**Comment by martin-martin** [comment]
I wouldn't mind doing some work on the responsiveness. I'm just not yet very experienced with this yet, so it would probably take longer if I do it. But I will gladly do some parts, and if there will be a team, I'm in. : )
Ryan, what does "Pressing Matter" mean? Is there a ETA for this?

**Comment by RyanCCollins** [comment]
I just added that so that we can highlight the issues that are most pressing.  No real ETA on it, but it means let's prioritize it above others.  We need this for the initial MVP, which we are getting fairly close to.

**Comment by zhangtreefish** [comment]
@ryancollins: Is it possible to get an updated Grommet version for our app? There has been some improvement on the responsiveness of their headline component: https://github.com/grommet/grommet/commit/21b39cbd189048a7bb21bd7c8d05635cf05bd2c6
