### ISSUE TITLE
Markdown content overflows article

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#85]

**Comment by RyanCCollins** [comment]
![screencapture-udacity-alumni-client-herokuapp-articles-22-1476385238229](https://cloud.githubusercontent.com/assets/13810084/19362754/e6c941e4-9155-11e6-974e-52e544798aec.png)

As you can see above, the markdown overflows the article.  If someone here would like to, please get this resolved so that the articles are functional.  Many thanks!!

**Comment by zhangtreefish** [comment]
Where is the bug at? :thinking_face: By clicking MarkdownNum at 'admin/content-dashboard' I got 404 land error.

**Comment by zhangtreefish** [comment]
@RyanCCollins: I put in a tiny PR fixing the redirect upon clicking articleTitle at 'admin/content-dashboard'; or perhaps it is intended that we will have a 'admin/articles/:id' route later? Can not imagine why such is needed. 
I was trying to fix the overflow with overflow:scroll, and saw that you had solved the problem with a much grand-scaled approach. Where did you get the markdown-body styles? Why is this quite essential stuff  included in "./MegaDraft/megadraft.scss"?
